version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379
  seed:
    build: .
    depends_on:
      - etcd
  node:
    build: .
    depends_on:
      - etcd