version: '2'
services:

  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://localhost:2379

  receiver:
    build: .
    depends_on:
      - etcd
    ports:
      - 10000:8080
    environment:
      SPRING_PROFILES_ACTIVE: receiver

  processor:
    build: .
    depends_on:
      - etcd
    environment:
      SPRING_PROFILES_ACTIVE: processor

  transmitter:
    build: .
    depends_on:
      - etcd
    environment:
      SPRING_PROFILES_ACTIVE: transmitter
    ports:
      - 20000:8080